### PR TITLE
[BINARY] : Bump binary to 1.69.7

### LINKED ISSUE #31: [DOCS] add a note that this bundle does not work with alpine
This bundle is downloading dart-sass automatically which is perfectly ok when running on windows, macos, linux. Except for some distro's like alpine. Alpine is quite popular for people using docker because of the image size. But this comes with a different libc, which is not the version dart-sass is compiled with. 

Their is no alternative download available with musl-libc. See https://github.com/sass/embedded-host-node/issues/155

### PR DESCRIPTION
**Pull request by LaurentSanson**
As it is mentioned in the [issue 31](https://github.com/SymfonyCasts/sass-bundle/issues/31), the sass binary has been updated and it now provides official releases for musl LibC and for Android.

Closes #31

### CODE REVIEW

**Comment by smnandre** [comment]
The stop_on_error seems to be ignored :/ i’ll look tomorrow

**Review by bocharsky-bw — COMMENTED** [review]
Great! This should finally close #31  🎉 

Though I wonder if the bumped version is the reason why tests fail here

**Comment by andersonamuller** [comment]
To work with `Alpine` we would still need to detect that on the `getBinaryName` method to add the `-musl`

**Comment by bocharsky-bw** [comment]
@andersonamuller would you like to open a PR for this change?

**Comment by bocharsky-bw** [comment]
Yeah sure, thanks for the head-ups though! If there's a volunteer who would like to help with necessary changes for Alipnie support in this bundle - feel free to take it

**Comment by LaurentSanson** [comment]
@bocharsky-bw , I've added the `-musl` option to get the binary file, but we still got errors. If you have any idea why, please let me know

File: src/SassBinary.php [hunk 1]
```diff
@@ -133,10 +133,10 @@ public function getBinaryName(): string
 
         if (str_contains($os, 'linux')) {
             if ('arm64' === $machine || 'aarch64' === $machine) {
-                return $this->buildBinaryFileName('linux-arm64');
+                return $this->buildBinaryFileName('linux-musl-arm64');
```
Comment (smnandre) [inline src/SassBinary.php:136]: That seems wrong to me... all linux should probably not use the musl version, or did i miss something ?

Comment (bocharsky-bw) [reply src/SassBinary.php:136]: yeah, sounds fair.. I suppose we need to use `musl` only for Alpine? Any ideas on how to check we're on exactly Alpine Linux distribution?

Comment (smnandre) [reply src/SassBinary.php:136]: That's what i'm looking for ... with no results for now.

Nothing in `php_uname` nothing in `$_ENV` or `$_SERVER ` ... maybe a configuration key ? :|

Comment (bocharsky-bw) [reply src/SassBinary.php:136]: ChatGPT suggests something like `file_exists('/etc/alpine-release')` - not sure 100% but it may work I suppose?

Comment (smnandre) [reply src/SassBinary.php:136]: I created a php:8.3-alpine docker image and downloaded this version: `dart-sass-1.69.6-linux-musl-arm64`

The binary works perfectly.

```php
string(5) "linux"
string(7) "aarch64"
string(5) "Linux"
string(12) "462bf4f33866"
```

So remains only the "detection" part (because i'm not sure if the arm64 will work on anything but a macos host)

Comment (smnandre) [reply src/SassBinary.php:136]: The `/etc/alpine-release works` !

Comment (smnandre) [reply src/SassBinary.php:136]: The following seems to work ... i'd rather have someone using Alpine test a bit more :) 

```php
        if (str_contains($os, 'linux')) {
            $baseName = file_exists('/etc/alpine-release') ? 'linux-musl' : 'linux';
            if ('arm64' === $machine || 'aarch64' === $machine) {
                return $this->buildBinaryFileName($baseName.'-arm64');
            }
            if ('x86_64' === $machine) {
                return $this->buildBinaryFileName($baseName.'-x64');
            }

            throw new \Exception(sprintf('No matching machine found for Linux platform (Machine: %s).', $machine));
        }
```

**Review by bocharsky-bw — COMMENTED** [review]
The code looks good to me now 👍 

Unfortunately, as you can see with my latest few commits - test failures are related here. Could you take a look?

**Comment by smnandre** [comment]
The errors seems to be only related to stop_on_error option right ?

**Comment by bocharsky-bw** [comment]
@smnandre yeah happens in `testSassOptionStopOnError()`

**Comment by smnandre** [comment]
I think it's related to recent changes in the async handling in sass. So we may remove temporary the test ? 👼

**Comment by bocharsky-bw** [comment]
Ah, that sounds possible... OK, I temporarily marked it as skipped. If anybody has ideas on how to fix it (or test that in a better way) - please, open a PR.

Thank you guys!
